import {
  createProviderDefinedToolFactoryWithOutputSchema,
  lazySchema,
  zodSchema,
} from '@ai-sdk/provider-utils';
import { z } from 'zod/v4';

/**
 * Schema for the apply_patch input - what the model sends.
 *
 * Refer the official spec here: https://platform.openai.com/docs/api-reference/responses/create#responses_create-input-input_item_list-item-apply_patch_tool_call
 *
 */
export const applyPatchInputSchema = lazySchema(() =>
  zodSchema(
    z.object({
      callId: z.string(),
      operation: z.discriminatedUnion('type', [
        z.object({
          type: z.literal('create_file'),
          path: z.string(),
          diff: z.string(),
        }),
        z.object({
          type: z.literal('delete_file'),
          path: z.string(),
        }),
        z.object({
          type: z.literal('update_file'),
          path: z.string(),
          diff: z.string(),
        }),
      ]),
    }),
  ),
);

/**
 * Schema for the apply_patch output - what we send back.
 */
export const applyPatchOutputSchema = lazySchema(() =>
  zodSchema(
    z.object({
      status: z.enum(['completed', 'failed']),
      output: z.string().optional(),
    }),
  ),
);

/**
 * Schema for tool arguments (configuration options).
 * The apply_patch tool doesn't require any configuration options.
 */
export const applyPatchArgsSchema = lazySchema(() => zodSchema(z.object({})));

/**
 * Type definitions for the apply_patch operations.
 */
export type ApplyPatchOperation =
  | {
      type: 'create_file';
      /**
       * Path of the file to create relative to the workspace root.
       */
      path: string;
      /**
       * Unified diff content to apply when creating the file.
       */
      diff: string;
    }
  | {
      type: 'delete_file';
      /**
       * Path of the file to delete relative to the workspace root.
       */
      path: string;
    }
  | {
      type: 'update_file';
      /**
       * Path of the file to update relative to the workspace root.
       */
      path: string;
      /**
       * Unified diff content to apply to the existing file.
       */
      diff: string;
    };

/**
 * The apply_patch tool lets GPT-5.1 create, update, and delete files in your
 * codebase using structured diffs. Instead of just suggesting edits, the model
 * emits patch operations that your application applies and then reports back on,
 * enabling iterative, multi-step code editing workflows.
 *
 * The tool factory creates a provider-defined tool that:
 * - Receives patch operations from the model (create_file, update_file, delete_file)
 * - Returns the status of applying those patches (completed or failed)
 */
/**
 * 中文：OpenAI 原生 `apply_patch` 的应用侧适配工厂。
 * 调用链：`openai.tools.applyPatch()` 创建带 `id: 'openai.apply_patch'` 的
 * provider-defined 工具 → Core `prepareTools` 保留其 id/args →
 * `prepareResponsesTools` 转成 OpenAI 请求的 `{ type: 'apply_patch' }` →
 * 模型返回 `apply_patch_call` → adapter 将它转成普通（非 `providerExecuted`）
 * tool-call → Core 调用调用方传入的 `execute` 来真正写入文件，并把 status/result
 * 作为下一轮输入。
 *
 * 所以这个 SDK 只统一 OpenAI 的调用格式和 Schema，绝不会在本仓库中应用 diff；
 * 也没有把它自动翻译为 Anthropic 的 text editor 或其他 Provider 的 function。
 */
export const applyPatchToolFactory =
  createProviderDefinedToolFactoryWithOutputSchema<
    {
      /**
       * The unique ID of the apply patch tool call generated by the model.
       */
      callId: string;

      /**
       * The specific create, delete, or update instruction for the apply_patch tool call.
       */
      operation: ApplyPatchOperation;
    },
    {
      /**
       * The status of the apply patch tool call output.
       * - 'completed': The patch was applied successfully.
       * - 'failed': The patch failed to apply.
       */
      status: 'completed' | 'failed';

      /**
       * Optional human-readable log text from the apply patch tool
       * (e.g., patch results or errors).
       */
      output?: string;
    },
    // No configuration options for apply_patch
    {}
  >({
    id: 'openai.apply_patch',
    inputSchema: applyPatchInputSchema,
    outputSchema: applyPatchOutputSchema,
  });

/**
 * The apply_patch tool lets GPT-5.1 create, update, and delete files in your
 * codebase using structured diffs. Instead of just suggesting edits, the model
 * emits patch operations that your application applies and then reports back on,
 * enabling iterative, multi-step code editing workflows.
 */
/**
 * 中文：OpenAI `apply_patch` 工具工厂的公开别名；上方工厂注释说明其完整的
 * 请求、应用侧执行和结果回传链路。
 */
export const applyPatch = applyPatchToolFactory;
